### ISSUE TITLE
Lab 9 peer review- Laura Amoroso

### ISSUE THREAD

**Issue by AmorosoLaura** [ivanmag22/computational-intelligence#4]
Hi Ivan,

I really appreciated your attempts and the variety of solutions that you tried, especially the segregation model that I did not try. I can give you some advices to improve your performances. 

- I suggest you to try a Steady State algorithm for some generation using a different kind of one-cut-crossover, a Mutation probaility that you tune according to the performances (decrease a little if you have a very positive trend, decreas it a little otherwise), and that should be enough for the instances 1 and 2. Here the crossover I mentioned:

    ```python
    def one_cut_crossover(ind1: Individual, ind2: Individual) -> Individual:
        offspring1=Individual(fitness_function, n_loci, tuple(ind1.genotype[:index]) + tuple(ind2.genotype[index:]))
        offspring2=Individual(fitness_function, n_loci, tuple(ind1.genotype[index:]) + tuple(ind2.genotype[:index]))
        return offspring1,offspring2
     ```
   or in your case:
   ```python
  def one_cut(g1, g2):
    cut = randint(0, PROBLEM_SIZE)
    return (g1[:cut] + g2[cut:]), (g1[cut:]+g2[:cut])
    ```

    that returns 2 children and the second one is formed by the second half of the first parent and the first part of the second. This kind of crossover seems to work really well for this problem.

- I think that parallel methods should be more suited for greater instances of the problem, although they might perform worse than the classical Steady State for lower instances, but try to choose very low values for the mutation probability, like 0.01, and use a probability also for the migration instead of doing it at certain iteration, so that you can tune both this parameters and adapt them to the trend of the fitness. 

- When using the island model try to differentiate the different islands in the sense that you use different mutation probabilities and different crossover, and in order to promote diversity you could apply a removal of the identical individuals or some other solution to apply upon stagnation. 

- You can also try to group similar individuals in the different islands according to their fitness or their genotype, so that different islands explore different parts of the solution space. 

- Ultimately parallel methods may require a lot of time and iterations, so may try to wait longer than 300 generations of stalling, because maybe thanks to the tuning of the parameters, your algorithm will be able to escape local optima. 

Unfortunately I did not reach the 1.0 value for the instances 5 and 10, so I can not suggest you the best strategy for those problems. However I hope that my little tips can be useful, let me know if you try something. 

Good luck!

**Comment by ivanmag22** [comment]
Hi Laura!
Your advices are very precious!

- I am confident that the *one-cut-crossover* that you have proposed could bring improvements
- As you said, I can improve my approach by treating the several niches/islands with *different mutation probabilities and hyper-paramaters*. Indeed, for the last one, it is not a good approach the one that uses the same values for all the islands or that stops to search in all the islands when we do not find a better individual: I have to think locally and not globally, because if I improve locally there could be chances to improve the global solution. So it is better to use different values and to stop eventually the exploration/exploitation in just a few ones that do not bring improvements.
- As I said in the README, I am not really sure to *group the individuals* by the genotype because there could be the risk to converge immediately because the individuals are too similar among them. But I know that there could be a way to group the individuals in order to retrieve better performances!
- I agree with you that *parallel methods* are not the best to work with problem with instance 1 and 2. Indeed one of its problems is the high number of fitness calls.

Thank you for the peer review!
Good luck you too!
