### ISSUE TITLE
Lab10 Peer Review - Lorenzo Ugoccioni s315734

### ISSUE THREAD

**Issue by LorenzoUgo** [ivanmag22/computational-intelligence#7]
HI Ivan!

I appreciated that your markdown file is clear and straight to the point, while the details stays as intro in the code part.

It's nice to see why different strategy are implemented and how different policy are applied to Q-Learning.

Overall, your code is well-written and I found the strategy pretty straight-forward so GOOD JOB!

It probably would have been better to make the graphs related to the training phase, and not to the test phase, so as to show how the agent's learning evolves.

It is only a pity that the percentage of defeat is greater than the percentage of draw. Probably if you had slightly rewarded the draw, the agent would have learned, when in doubt, not to lose.

Good luck for the final project!!

**Comment by ivanmag22** [comment]
Hi Lorenzo!
Thank you for the review!
You're right:

- maybe it could be more understandable a graph about the training phase than the test phase.
- I had some doubts about the rewards, but after some comments you and other colleagues have convinced me to fix them in order to get better performances.

Good luck for the project! :)
