### ISSUE TITLE
Peer Review Lab 10 -Raffaele Viola s309063 

### ISSUE THREAD

**Issue by RaffaeleViola** [ivanmag22/computational-intelligence#8]
Your code is well written and the model is well designed. The approach leads to almost perfect results but here my considerations that could help to further improve them: 

- You could find a better trainer (for example a MinMaxPlayer) in order to help your model to learn better moves and reduce the convergence steps.
- You could update the qtable by traversing the trajectory in reverse order after a complete game. In this way you would immediately penalize the strategies (as a whole) that lead to losing.
- When you create a new entry in the qtable you could filter the already taken actions in order to reduce the memory usage of the table.

Overall you achieved good results, these are minor suggestions.

**Comment by ivanmag22** [comment]
Hi Raffaele!
Thank you for the review! I'll keep in consideration your advices, especially the first two.
- As you've seen, I've tried only the random player as trainer, but using a Q-agent or a MinMax player as trainer could be a good idea in order to get better results.
- I'll pay more attention on the Q-table, especially on the traversed states.
Good luck for the project!! :)
